#!/bin/bash

### THIS SCRIPT DEPLOYS A "TOR ROUTER" ON A eth1 INTERFACE
### PLEASE, RUN IT ON A CLEAN RASPBIAN INSTALLATION, AND WITH "sudo -i"

## UPDATES AND UPGRADES THE SYSTEM
sudo apt update
sudo apt upgrade -y

## SETS TO TRUE THE DIALOGS OF THE IPTABLES-PERSISTENT INSTALL, THIS WILL SAVE THE IPTABLES ACTUAL CONFIG
echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections

## INSTALLS THE REQUIRED PACKAGES
sudo apt install -y tor tor-arm isc-dhcp-server iptables-persistent

## CREATES THE NETWORK CONFIG
sudo echo "
auto lo
auto eth0
auto eth1

iface lo inet loopback
iface eth0 inet static
        address 192.168.1.141
        netmask 255.255.255.0
        gateway 192.168.1.1

iface eth1 inet static
        address 192.168.45.1
        netmask 255.255.255.0
" >> /etc/network/interfaces

## UNCOMMENTS net-ipv4.ip_forward=1 AT /etc/sysctl.conf
sudo sed -i '/net.ipv4.ip_forward=1/s/^#//g' /etc/sysctl.conf

## ENABLES IP_FORWARDING
sudo echo 1 > /proc/sys/net/ipv4/ip_forward
sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

## CREATES DHCP SERVER CONFIG

echo "subnet 192.168.45.0 netmask 255.255.255.0 {" >> /etc/dhcp/dhcpd.conf
echo "range 192.168.45.10 192.168.45.50;" >> /etc/dhcp/dhcpd.conf
echo "option broadcast-address 192.168.45.255;" >> /etc/dhcp/dhcpd.conf
echo "option routers 192.168.45.1;" >> /etc/dhcp/dhcpd.conf
echo "default-lease-time 600;" >> /etc/dhcp/dhcpd.conf
echo "max-lease-time 7200;" >> /etc/dhcp/dhcpd.conf
echo "option domain-name "local";" >> /etc/dhcp/dhcpd.conf
echo "option domain-name-servers 192.168.45.1;" >> /etc/dhcp/dhcpd.conf
echo "}" >> /etc/dhcp/dhcpd.conf

## UNCOMMENTS authoritative LINE AT /etc/dhcp/dhcpd.conf
sudo sed -i '/authoritative;/s/^#//g' /etc/dhcp/dhcpd.conf

## SETS INTERFACE TO eth1
sudo sed -i '/INTERFACESv4=""/c\INTERFACESv4="eth1"' /etc/default/isc-dhcp-server

## ENABLES LOG FILE FOR TOR
sudo touch /var/log/tor/notices.log
sudo chown debian-tor /var/log/tor/notices.log
sudo chmod 644 /var/log/tor/notices.log

## CREATES TOR CONFIG FILE
echo  Log notice file /var/log/tor/notices.log  >> /etc/tor/torrc &&
echo  VirtualAddrNetworkIPv4 10.192.0.0/10  >> /etc/tor/torrc &&
echo  AutomapHostsSuffixes .onion,.exit  >> /etc/tor/torrc &&
echo  AutomapHostsOnResolve 1  >> /etc/tor/torrc &&
echo  TransPort 9040  >> /etc/tor/torrc && 
echo  TransListenAddress 192.168.45.1  >> /etc/tor/torrc &&
echo  DNSPort 53  >> /etc/tor/torrc && 
echo  DNSListenAddress 192.168.45.1  >> /etc/tor/torrc &&
echo  ControlPort 9051  >> /etc/tor/torrc

## DENIES SSH TO ALL ETH1 RANGE
echo "sshd: 192.168.45.0/255.255.255.0" >> /etc/hosts.deny

## DELETES AUTOGENERATED resolv.conf AND ADDS OPENNIC DNS SERVERS
sudo rm /etc/resolv.conf
echo "nameserver 185.208.208.141" >> /etc/resolv.conf
echo "nameserver 172.104.136.243" >> /etc/resolv.conf

## GENERATES IPTABLES
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -I FORWARD -d 192.168.1.0/24 -i eth1 -j DROP
sudo iptables -I FORWARD -d 192.168.0.0/24 -i eth1 -j DROP
sudo iptables -I FORWARD -d 172.16.0.0/12 -i eth1 -j DROP
sudo iptables -I FORWARD -d 224.0.0.0/4 -i eth1 -j DROP
sudo iptables -I FORWARD -d 240.0.0.0/5 -i eth1 -j DROP
sudo iptables -I FORWARD -d 127.0.0.0/8 -i eth1 -j DROP
sudo iptables -I FORWARD -d 10.0.0.0/8 -i eth1 -j DROP
sudo iptables -t nat -A PREROUTING -i eth1 -p tcp -m tcp --dport 22 -j REDIRECT --to-ports 22
sudo iptables -t nat -A PREROUTING -i eth1 -p udp -m udp --dport 53 -j REDIRECT --to-ports 53
sudo iptables -t nat -A PREROUTING -i eth1 -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j REDIRECT --to-ports 9040

## SAVES IPTABLES
sudo iptables-save >> /etc/iptables/rules.v4

## ENABLES NEEDED SERVICES
sudo systemctl enable isc-dhcp-server
sudo service isc-dhcp-server start
sudo systemctl enable tor
sudo service tor start

